### ISSUE TITLE
FORMAT ERROR after retry

### ISSUE THREAD

**Issue by vitorenesduarte** [huaban/erlzk#18]
Hi,

I'm seeing this:

```bash
17:16:30.770 [error] FORMAT ERROR: "Connection to ~p:~p timeout while waiting for connect reply: ~p~n" [{17 ,17,0,4},2181]
```

It seems to come from [here](https://github.com/huaban/erlzk/blob/100084c5685cdc4a0964e327ae5fb9702799355d/src/erlzk_conn.erl#L424).

**Comment by zolazhou** [comment]
Yes, thank you for report.
