### ISSUE TITLE
heartbeat not fully implemented?

### ISSUE THREAD

**Issue by kevinbombadil** [huaban/erlzk#7]
I ran into this problem when deliberately dropping all packets between client and one connected server - I expected to see it reconnect to one of the other servers but instead it just sat there. 
If I bounce the connected server instead the fail-over is fine - but if I interrupt the connection it fails. 
Looking at the code it seems like the client is not sending heartbeats to the server. Comparing it to the java I can see ping defined in ZooDefs.java but the matching operation does not appear in erlzk_codec.erl.
I'll read the java some more to understand what needs to be done to make this work - can you let me know what the position is with heartbeats from your side.  --- thanks k

**Comment by megayu** [comment]
https://github.com/huaban/erlzk/blob/master/src/erlzk_conn.erl#L203

I'm using the same logical like official java client did.

**Comment by kevinbombadil** [comment]
I missed that bit - and the way handle-call timeouts are used to trigger the operation.. 

But still, if there are not message coming back from the server nothing will happen. So in my test (where I don't drop the server, but just drop the packets) it won't reconnect. 

I think this bit in ClientCnxn.java is what is missing :

```java
     if (to <= 0) {
         throw new SessionTimeoutException(
                 "Client session timed out, have not heard from server in "
                         + clientCnxnSocket.getIdleRecv() + "ms"
                         + " for sessionid 0x"
                         + Long.toHexString(sessionId));
     }
```

.. this depends on a 'lasthead' timestamp which is updated every time something is received from the server - see calls to 'updateLasthead' in clientCnxnSocketNIO.doIO.

On way to do this could be to have a separate process (maybe an fsm) that acts as a timer which gets reset evert time something is recieved from the server. If its not reset in time it can send a message back to erlzk_conn telling it to reconnect. 

it would then do the same thing as this bit of code in erlzk_conn:

```erlang
handle_info({tcp_closed, _Port}, State=#state{host=Host, port=Port, monitor=Monitor}) ->
    error_logger:error_msg("Connection to ~p:~p is broken, reconnect now~n", [Host, Port]),
    notify_monitor_server_state(Monitor, disconnected, Host, Port),
```

Anyway - please let me know if you think I've missed something. I can try and get this bit working and send the change back if you'd like.. thanks k

**Comment by megayu** [comment]
You are right, and yes, any support is welcome.

**Comment by kevinbombadil** [comment]
Cool. I'll get back to this over the next couple of weeks. I'd also like to implement KillSession - which I could do on a separate fork - I've developed a work-around for it in the meantime but it would be nice for it to be part of erlzk. 
https://curator.apache.org/apidocs/org/apache/curator/test/KillSession.html

**Comment by megayu** [comment]
Actually i just found this feature on my todo list of this project, close session then reconnect a new one if there is no package received from server in 2 / 3 * timeout.

And there are more in my list.

* readonly connection
* persistent watcher (after receive watched event just register a new watcher immediately)
* high-level api, like delete_all, create_all (like mkdir -p)
* recipe

**Comment by kevinbombadil** [comment]
doh!  I'll have a think about them ;-)

**Comment by kevinbombadil** [comment]
Hi megayu - I have combined the two changes - KillSession and the heartbeat watcher - into my fork - allow a little more time for testing and I'll make a pull request for it soon. Thanks - k

**Comment by kevinbombadil** [comment]
Pull request created - let me know how it looks to you. thanks - K

**Comment by zugolosian** [comment]
https://github.com/huaban/erlzk/pull/8

**Comment by megayu** [comment]
Thanks for your work, and sorry for taking so long.
